version: "3.8"

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - FLASK_ENV=development
    command: python app.py
